### ISSUE TITLE
The prediction function skips a row when outputting "test_results.tsv" results

### ISSUE THREAD

**Issue by Alaa-1** [instadeepai/tunbert#1]
After training the module using `finetuning_sa_tdid.sh ` , then running predictions on the `test.tsv`, the output of the prediction which gets written in `test_results.tsv` I noticed that the test file and the test_results file don't have same number of rows. 

for example the `tunbert/dev-data/sentiment_analysis_tsac/test.tsv` file that comes with your repo has 5 sentences/rows. When I run the predictions the `tunbert/finetuning_tsac/test_results.tsv` file outputs only 4 sentences/rows. 

![my_issue](https://user-images.githubusercontent.com/27267152/124354021-cc900280-dc01-11eb-88e7-3ca7a896d7a6.png)

Update: After spending more time tinkering with the model, It truns out that I didn't spot a minor issue when I was dealing with headers. Sorry for the inconvenience and the false issue. Great work, I really enjoyed it ^^

**Comment by hassibatej** [comment]
Amazing !
